name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Install PulseAudio Library and Headers
        run: |
          sudo apt-get update
          sudo apt-get install -y libpulse-dev
      -
        name: Build
        run: |
          cmake -H. -Bbuild
          cmake --build build
      -
        name: Test
        run: ./build/sio_list_devices

